export const GET_USERS = 'GET_USERS';
export const FAILED_TO_GET_USERS = 'FAILED_TO_GET_USERS';
export const LOGIN = 'LOGIN';
export const GET_MOVIES= 'GET_MOVIES';
export const GET_MOVIES_WATCHED= 'GET_MOVIES_WATCHED';
export const FAILED_TO_GET_MOVIES_WATCHED= 'FAILED_TO_GET_MOVIES_WATCHED';
export const FAILED_TO_GET_MOVIES= 'FAILED_TO_GET_MOVIES';
export const FAILED_TO_LOGIN = 'FAILED_TO_LOGIN';